<a href="https://colab.research.google.com/github/rixprakash/Jarheads/blob/main/Project%202/SCRIPTS/Project2StockMarket.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
! git clone https://github.com/rixprakash/Jarheads

fatal: destination path 'Jarheads' already exists and is not an empty directory.

In [3]:
import pandas as pd
import os
! git clone https://github.com/rixprakash/Jarheads

# Define file paths
vix_file = '/content/Jarheads/Project 2/DATA/CBOE Volatility Index Historical Data.csv'
spy_file = '/content/Jarheads/Project 2/DATA/SPY ETF Stock Price History.csv'
vix_df = pd.read_csv(vix_file)
spy_df = pd.read_csv(spy_file)

fatal: destination path 'Jarheads' already exists and is not an empty directory.

In [7]:

if not os.path.exists(vix_file) or not os.path.exists(spy_file):
  print("Error: One or both input files not found.")
else:
  try:
    # Convert the 'Date' column to datetime objects
    vix_df['Date'] = pd.to_datetime(vix_df['Date'])
    spy_df['Date'] = pd.to_datetime(spy_df['Date'])

    # Merge the DataFrames based on the 'Date' column
    marketdata = pd.merge(vix_df, spy_df, on='Date', how='inner')

    # Save the merged DataFrame to a new CSV file
    marketdata.to_csv(output_file, index=False)
    print(f"Merged data saved to {output_file}")

  except Exception as e:
    print(f"An error occurred: {e}")
marketdata.head()

Merged data saved to /content/Jarheads/Project 2/DATA/merged_data.csv

,Date,Price_x,Open_x,High_x,Low_x,Vol._x,Change %_x,Price_y,Open_y,High_y,Low_y,Vol._y,Change %_y
0,2025-03-03,22.78,19.83,24.31,19.25,NaN,16.05%,583.77,596.18,597.34,579.90,74.25M,-1.75%
1,2025-02-28,19.63,21.21,22.40,19.05,NaN,-7.10%,594.18,585.56,594.72,582.44,88.74M,1.56%
2,2025-02-27,21.13,18.25,21.47,17.67,NaN,10.63%,585.05,596.85,598.02,584.65,74.20M,-1.60%
3,2025-02-26,19.10,18.96,20.06,17.83,NaN,-1.70%,594.54,595.93,599.58,591.86,43.32M,0.05%
4,2025-02-25,19.43,19.09,21.48,18.85,NaN,2.37%,594.24,597.15,597.89,589.56,58.27M,-0.50%

In [8]:
marketdata = marketdata.rename(columns=lambda x: x.replace('_x', '_VIX'))
marketdata = marketdata.rename(columns=lambda x: x.replace('_y', '_SPY'))
marketdata.head()

,Date,Price_VIX,Open_VIX,High_VIX,Low_VIX,Vol._VIX,Change %_VIX,Price_SPY,Open_SPY,High_SPY,Low_SPY,Vol._SPY,Change %_SPY
0,2025-03-03,22.78,19.83,24.31,19.25,NaN,16.05%,583.77,596.18,597.34,579.90,74.25M,-1.75%
1,2025-02-28,19.63,21.21,22.40,19.05,NaN,-7.10%,594.18,585.56,594.72,582.44,88.74M,1.56%
2,2025-02-27,21.13,18.25,21.47,17.67,NaN,10.63%,585.05,596.85,598.02,584.65,74.20M,-1.60%
3,2025-02-26,19.10,18.96,20.06,17.83,NaN,-1.70%,594.54,595.93,599.58,591.86,43.32M,0.05%
4,2025-02-25,19.43,19.09,21.48,18.85,NaN,2.37%,594.24,597.15,597.89,589.56,58.27M,-0.50%